export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // Paddle Sandbox
  paddleApiKeySandbox: process.env.PADDLE_API_KEY_SANDBOX ?? "",
  paddleWebhookSecretSandbox: process.env.PADDLE_WEBHOOK_SECRET_SANDBOX ?? "",
  paddleProductIdStarterSandbox: process.env.PADDLE_PRODUCT_ID_STARTER_SANDBOX ?? "",
  paddlePriceIdStarterSandbox: process.env.PADDLE_PRICE_ID_STARTER_SANDBOX ?? "",
  paddleProductIdProSandbox: process.env.PADDLE_PRODUCT_ID_PRO_SANDBOX ?? "",
  paddlePriceIdProSandbox: process.env.PADDLE_PRICE_ID_PRO_SANDBOX ?? "",
  paddleProductIdAgencySandbox: process.env.PADDLE_PRODUCT_ID_AGENCY_SANDBOX ?? "",
  paddlePriceIdAgencySandbox: process.env.PADDLE_PRICE_ID_AGENCY_SANDBOX ?? "",
  // Paddle Live
  paddleApiKeyLive: process.env.PADDLE_API_KEY_LIVE ?? "",
  paddleWebhookSecretLive: process.env.PADDLE_WEBHOOK_SECRET_LIVE ?? "",
  paddleProductIdStarterLive: process.env.PADDLE_PRODUCT_ID_STARTER_LIVE ?? "",
  paddlePriceIdStarterLive: process.env.PADDLE_PRICE_ID_STARTER_LIVE ?? "",
  paddleProductIdProLive: process.env.PADDLE_PRODUCT_ID_PRO_LIVE ?? "",
  paddlePriceIdProLive: process.env.PADDLE_PRICE_ID_PRO_LIVE ?? "",
  paddleProductIdAgencyLive: process.env.PADDLE_PRODUCT_ID_AGENCY_LIVE ?? "",
  paddlePriceIdAgencyLive: process.env.PADDLE_PRICE_ID_AGENCY_LIVE ?? "",
  paddleEnvironment: (process.env.PADDLE_ENVIRONMENT ?? "sandbox") as "sandbox" | "live",
};
